//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int ORD_ID { get; set; }
        public int CLI_ID { get; set; }
        public int DEL_ID { get; set; }
        public int PAY_ID { get; set; }
        public int PRO_ID { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual DELIVERY_TYPES DELIVERY_TYPES { get; set; }
        public virtual PAYMENTS PAYMENTS { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
