//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Order = new HashSet<Order>();
        }
        [Required(ErrorMessage = "Id can't be empty")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name can't be empty")]
        [MinLength(3, ErrorMessage = "Minimum name length is 3")]
        [MaxLength(40, ErrorMessage = "Maximum name length is 40")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Price can't be empty")]
        [Range(1, 20)]
        public double Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
