//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Payment_id { get; set; }
        public int Ord_id { get; set; }
        public double Total_value { get; set; }
        public double Delivery_cost { get; set; }
        public int Discount { get; set; }
        public double Pay_value { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
