//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
        public double UNIT_PRICE { get; set; }
        public int QUANTITY { get; set; }
        public int WAR_ID { get; set; }
        public int PRODUCER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        public virtual PRODUCERS PRODUCERS { get; set; }
        public virtual WAREHOUSES WAREHOUSES { get; set; }
    }
}
