//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producer()
        {
            this.Product = new HashSet<Product>();
        }

        [Required(ErrorMessage = "Id can't be empty")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name can't be empty")]
        [MinLength(3, ErrorMessage = "Minimum name length is 3")]
        [MaxLength(40, ErrorMessage = "Maximum name length is 40")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Warehouse id can't be empty")]
        public int War_id { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
